pag_dic/apps/personas/urls.py
from django.urls import path, re_path
from django.contrib.auth.decorators import login_required #<--- Restringir las vistas a usuarios
#____________________________________
from apps.personas.views import(
	lista_personas,
	registrar_persona,
	eliminar_persona,
	sorteo,
	editar_persona,
)
#____________________________________
app_name= 'personas_app'

urlpatterns= [
	path('', lista_personas.as_view(), name='lista_personas'),
	path('inscribir/', login_required(registrar_persona.as_view()), name='registrar_persona'),
	path('eliminar/<pk>/', login_required(eliminar_persona.as_view()), name='eliminar_persona'),
	path('editar/<int:pk>/', login_required(editar_persona.as_view()), name= 'editar_persona'),
	path('sortear/', login_required(sorteo), name='sorteo'),
]

pag_dic/apps/usuarios/urls.py
from django.conf.urls import url
from apps.usuarios.views import registrar_usuario

app_name= 'usuarios_app'

urlpatterns=[
	url('registrar/', registrar_usuario.as_view(), name='registrar')
	]
	

pag_dic/pag_dic/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth.views import (
        LoginView,
        LogoutView,
        PasswordResetView,
        PasswordResetDoneView,
        PasswordResetConfirmView,
        PasswordResetCompleteView,
        )

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.personas.urls', namespace='personas_app')),
    path('usuario/', include('apps.usuarios.urls', namespace='usuarios_app')),

    #login
    path('accounts/login/', LoginView.as_view(template_name='index.html'), name='login'),
    #logout
    path('logout/', LogoutView.as_view(), name='logout'),

    #recuperar clave
    path('reset/password_reset', PasswordResetView.as_view(template_name='registration/password_reset_form.html', email_template_name="registration/password_reset_email.html"), name = 'password_reset'),
    path('reset/password_reset_done', PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name = 'password_reset_done'),
    re_path(r'^reset/(?P<uidb64>[0-9A-za-z_\-]+)/(?P<token>.+)/$', PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name = 'password_reset_confirm'),
    path('reset/done', PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html') , name = 'password_reset_complete'),

    ]

pag_dic/apps/personas/models.py
from django.db import models
from django.contrib.auth.models import User
from django.http import request
# Create your models here.

'''def get_user_id(request):
		username_logged=request.user.get_username()
		id_username= User.objects.get(username=username_logged)
		pk_user= id_username.id
		pk_user= int(pk_user)
		return pk_user'''


class Persona(models.Model):

	usuario_pk= models.ForeignKey(User, on_delete=models.CASCADE, default='1')
	nombre= models.CharField('Nombre', max_length=20)
	apellido= models.CharField('Apellido', max_length=20)
	email= models.EmailField('Email', blank=True)

	def __str__(self):
		return 'Id:{} Nombre:{} Apellido:{}'.format(self.id, self.nombre, self.apellido)

pag_dic/apps/usuarios/models.py
from django.db import models

# Create your models here.

pag_dic/apps/personas/forms.py
from django import forms
from apps.personas.models import Persona

class persona_form(forms.ModelForm):

	class Meta:
		model= Persona

		fields= [
			'nombre',
			'apellido',
			'email'
		]

		labels= {
			'nombre': 'Nombre',
			'apellido': 'Apellido',
			'email': 'Email'
		}

		widgets= {
			'nombre': forms.TextInput(attrs={'class': 'form-control'}),
			'apellido': forms.TextInput(attrs={'class': 'form-control'}),
			'email': forms.TextInput(attrs={'class': 'form-control'}),
		}

pag_dic/apps/usuarios/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class formato_usuario(UserCreationForm):

	class Meta:
		model= User
		fields= [
				'username',
				'first_name',
				'last_name',
				'email',
			]
		labels= {
				'username': 'Nombre de Usuario',
				'first_name': 'Nombre',
				'last_name': 'Apellido',
				'email': 'Correo',
		}

pag_dic/apps/personas/views.py
from django.shortcuts import render
from django.core.mail import send_mail
from django.urls import reverse_lazy
from django.http import HttpResponse, request
from django.contrib.auth.models import User
import random
#__________________________________
from .models import Persona
from .forms import persona_form
#__________________________________
from django.views.generic import(
	ListView,
	CreateView,
	DeleteView,
	TemplateView,
	UpdateView,
)


class lista_personas(ListView):
	template_name= 'personas/lista_personas.html'
	model= Persona
	context_object_name= 'personas'

class registrar_persona(CreateView):
	template_name= 'personas/registrar_personas.html'
	model= Persona
	form_class= persona_form
	success_url= reverse_lazy('personas_app:lista_personas')

class eliminar_persona(DeleteView):
	model= Persona
	template_name= 'personas/eliminar_personas.html'
	success_url= reverse_lazy('personas_app:lista_personas')

class editar_persona(UpdateView):
	model= Persona
	template_name= 'personas/editar_persona.html'
	form_class= persona_form
	success_url= reverse_lazy('personas_app:lista_personas')

def sorteo(request):
	#prueba id
	''''username_logged=request.user.get_username()
				id_username= User.objects.get(username=username_logged)
				pk_user= id_username.id
				print (pk_user)
    #prueba de obtener el id del user logueado
	current_user = request.user
				print (f'Id del Usuario logged: {current_user.id}')'''
	
	#__________________________________________________
	#peronas= Persona.objects.all()
	#pks= list(personas)

	#random.shuffle(pks)
	#pks.append(pks[0])
			
	#for p in range(len(pks) - 1):
		#e=Persona.objects.get(pk=str(pks[p]))
		#n=Persona.objects.get(pk=str(pks[p + 1]))

		#print(f'{e.email} ---> {n.nombre}')
		
		#send_mail('Tu amigo secretro [ENSAYO]!',
			#f'Tu AMIGO SECRETO [ENSAYO] para este intercambio navideño es: {n.nombre}!',
			#'amigo.secreto.dic2019@gmail.com',
			#[f'{e.email}'],)
		#print('enviado!')
	#________________________________________________________________________________________
	return render(request, 'sorteo/sorteo.html')

def get_user_id(request):
	username_logged=request.user.get_username()
	id_username= User.objects.get(username=username_logged)
	pk_user= id_username.id
	return pk_user

pag_dic/apps/usuarios/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.views.generic import CreateView
from django.urls import reverse_lazy
# Create your views here.
from apps.usuarios.forms import formato_usuario

class registrar_usuario(CreateView):
	models= User
	template_name= 'usuarios/registrar_usuario.html'
	form_class= formato_usuario
	success_url= reverse_lazy('personas_app:lista_personas')

pag_dic/templates/base/base.html
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">

	{% block extrastatic %}
	{% endblock %}

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
	<title>{% block title %} Intercambio Navidad {% endblock %}</title>

</head>
<body>

<div class="container">

	{% block navbar %}
		<div>
			<nav class="navbar navbar-inverse">
			 	<ul class="nav navbar-nav">
			 		<li><a href="{% url 'personas_app:lista_personas' %}">Home</a></li>
			 		
			 		{% if user.is_active %}
			 		<li><a href="{% url 'personas_app:registrar_persona' %}" >Inscribir
			 		</a></li>
			 		{% endif %}
			 		
			 		{% if user.is_active %}
			 		<li><a class="btn btn-danger" href="{% url 'personas_app:sorteo' %}">Sortear</a></li>
					{% endif %}
					 
					{% if not user.is_active %}
					<li><a href="{% url 'usuarios_app:registrar' %}" >Registrarse</a></li>
					{% endif %}
					 
					{% if not user.is_active %}
					 <li><a href="{% url 'login' %}" >Login</a></li>
					{% endif %}
			 		
			 		{% if user.is_active %}
			 		<li><a href="{% url 'logout' %}" >Salir</a></li>
			 		{% endif %}
			 		
			 	</ul>
			</nav>
		</div>
	{% endblock %}


	{% block content %}
	{% endblock %}


	{% block footer %}
	{% endblock%}

</div>

	{% block extrajs %}
	{% endblock %}

</body>
</html>

pag_dic/templates/index.html
{% extends 'base/base.html' %}

{% block content %}
<div>
    <h3>
        Iniciar Sesion
    </h3>
</div>
<form method="post">
    {% csrf_token %}
     <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="form-group">
                <label for="username">Nombre de usuario:</label>
                <input class="form-control" type="text" name="username">
           </div>
        </div>
    </div>    
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="form-group">
                <label for="username">Contraseña:</label>
                <input class="form-control" type="password" name="password">
           </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="form-group">
                <a href="{% url 'password_reset'  %}">Olvidé mi contraseña</a>
                <input class="btn btn-primary" type="submit" value="Ingresar">
           </div>
        </div>
    </div>
</form>


{% endblock %}

pag_dic/templates/personas/editar_persona.html
{% extends 'base/base.html' %}

{% block content %}
<form method="POST">
	{% csrf_token %}
	{{ form.as_p }}
	<button type="submit">Guardar</button>
</form>

{% endblock %}

pag_dic/templates/personas/eliminar_personas.html
{% extends 'base/base.html' %}

{% block content %}
<form method="POST">
	{% csrf_token %}
	
	<h3>¿Desea eliminar a {{ object.nombre }} {{ object.apellido }} de la lista?</h3> 

	<button class="btn btn-danger" >Si, eliminar</button>
	<a class="btn btn-default" href="{% url 'personas_app:lista_personas' %}">Cancelar</a>
</form>

{% endblock %}

pag_dic/templates/personas/lista_personas.html
{% extends 'base/base.html' %}
{% block content %}
<!DOCTYPE html>
<html>
<head>
	<title>Lista de Personas</title>
</head>
<body>
	<h1>Lista Personas</h1>
	<table class="table">

			<thead >
				<tr>
					<td>Id</td>
					<td>Nombre</td>
					<td>Apellido</td>
					<td>Correo</td>
					<td>Acción</td>
				</tr>
			</thead>

			<tbody>
				{% if object_list %}
				{% for personas in object_list %}
				<tr>
					<td>{{ personas.id }}</td>
					<td>{{ personas.nombre }}</td>
					<td>{{ personas.apellido }}</td>
					<td>{{ personas.email }}</td>
					<td >
						<a class="btn btn-success" href="{% url 'personas_app:editar_persona' personas.id %}">Editar</a>
						<a class="btn btn-danger" href="{% url 'personas_app:eliminar_persona' personas.id %}">Eliminar</a>
						
					</td>
				</tr>
				{% endfor %}

				{% else %}
				<h1>No hay registro</h1>
				{% endif %}
			</tbody>
	</table>
</body>
</html>
{% endblock %}

pag_dic/templates/personas/registrar_personas.html
{% extends 'base/base.html' %}

{% block content %}
<h3>Agregar Persona</h3>
<form method="POST">
	{% csrf_token %}
	{{ form.as_p }}
	<button type="submit">Guardar</button>
</form>
{% endblock %}

pag_dic/templates/sorteo/sorteo.html
{% extends 'base/base.html' %}

{% block content %}
<!DOCTYPE html>
<html>
<head>
	<title>Sorteo</title>
</head>
<body>
	<h1>Sorteo Realizado!, informacion envia al correo de los participantes.</h1>
	<a class="btn btn-default" href="{% url 'personas_app:lista_personas' %}">Volver</a>
</body>
</html>
{% endblock %}

pag_dic/templates/usuarios/registrar_usuario.html
{% extends 'base/base.html' %}
{% block content %}

<div>
	<h3>Registro de Usuario</h3>
</div>
<form method="post">
	{% csrf_token %}
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label >Nombre de usuario</label>
				<input class="form-control" type="text" name="username">
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label>Nombre</label>
				<input class="form-control" type="text" name="first_name">
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label >Apellido</label>
				<input class="form-control" type="text" name="last_name">
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label >Correo</label>
				<input class="form-control" type="text" name="email">
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label >Contraseña</label>
				<input class="form-control" type="password" name="password1">
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label >Confirmar contraseña</label>
				<input class="form-control" type="password" name="password2">
			</div>
		</div>
	</div>
	
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<button class="btn btn-primary "type="submit">Guardar</button>
			</div>
		</div>
	</div>
	
</form>
{% endblock %}